version: 2.1
variables:
- group: my-variable-group
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
          ci-build-id: 'testing-commit-${CIRCLE_SHA1}'